import React, { useState, useRef, useEffect } from 'react';
import { Menu, User, ArrowRight, Mic, X, Send, Plus, Sparkles, Video, Lightbulb, MoreHorizontal } from 'lucide-react';
import { HfInference } from '@huggingface/inference';

const NebulaEdgeApp = () => {
  const [currentPage, setCurrentPage] = useState('splash');
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isRecording, setIsRecording] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [apiKey, setApiKey] = useState('');
  const [tempApiKey, setTempApiKey] = useState('');
  const [apiSaved, setApiSaved] = useState(false);
  const recordingInterval = useRef(null);

  const handleSaveApiKey = () => {
    setApiKey(tempApiKey);
    setApiSaved(true);
    setTimeout(() => setApiSaved(false), 2000);
  };

  // Logic for the Voice Orb Timer
  useEffect(() => {
    if (isRecording) {
      recordingInterval.current = setInterval(() => setRecordingTime(prev => prev + 1), 1000);
    } else {
      if (recordingInterval.current) clearInterval(recordingInterval.current);
      setRecordingTime(0);
    }
    return () => clearInterval(recordingInterval.current);
  }, [isRecording]);

  const formatTime = (s) => `${Math.floor(s / 60).toString().padStart(2, '0')}:${(s % 60).toString().padStart(2, '0')}`;

  // MAIN CHAT FUNCTION
  const handleSendMessage = async (customPrompt = null) => {
    const text = customPrompt || inputValue;
    if (!text.trim()) return;
    if (!apiKey) {
      setMessages(prev => [...prev, { role: 'error', content: "Set HF API Token in Settings!" }]);
      return;
    }

    setMessages(prev => [...prev, { role: 'user', content: text }]);
    setInputValue('');

    try {
      const hf = new HfInference(apiKey);
      const response = await hf.chatCompletion({
        model: "Qwen/Qwen2.5-72B-Instruct",
        messages: [{ role: "user", content: text }],
        max_tokens: 500,
      });
      const reply = response.choices[0].message.content;
      setMessages(prev => [...prev, { role: 'assistant', content: reply }]);
    } catch (e) {
      setMessages(prev => [...prev, { role: 'error', content: "AI Error: Check your Token." }]);
    }
  };

  // IMAGE GENERATION FUNCTION
  const handleCreateImage = async () => {
    if (!apiKey) {
      alert("Please set your API key in settings!");
      return;
    }
    const promptText = prompt("Describe the image you want to create:");
    if (!promptText) return;

    setMessages(prev => [...prev, { role: 'user', content: `Creating image: ${promptText}` }]);

    try {
      const hf = new HfInference(apiKey);
      const blob = await hf.textToImage({
        model: 'black-forest-labs/FLUX.1-dev',
        inputs: promptText,
      });
      const url = URL.createObjectURL(blob);
      setMessages(prev => [...prev, { 
        role: 'assistant', 
        content: <div className="space-y-2">
                   <img src={url} alt="AI Gen" className="w-full rounded-xl border border-gray-700 shadow-2xl" />
                   <p className="text-xs text-gray-500 text-center">Generated by FLUX.1</p>
                 </div> 
      }]);
    } catch (e) {
      alert("Image creation failed.");
    }
  };

  // SPLASH SCREEN
  if (currentPage === 'splash') {
    return (
      <div className="h-screen bg-[#0a0e27] flex flex-col items-center justify-center p-8 text-center">
        <h1 className="text-7xl font-bold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent mb-4">Gemini</h1>
        <p className="text-gray-400 mb-8">Official Omni-modal Assistant</p>
        <button onClick={() => setCurrentPage('home')} className="bg-blue-600 text-white px-10 py-4 rounded-full flex items-center gap-2">
          Get Started <ArrowRight size={20}/>
        </button>
      </div>
    );
  }

  // HOME / CHAT SCREEN
  return (
    <div className="h-screen bg-[#0a0e27] flex flex-col text-white">
      {/* Dynamic Screen Rendering */}
      {currentPage === 'home' && (
        <>
          <div className="flex justify-between p-4 border-b border-gray-800">
            <Menu className="text-gray-400" onClick={() => setCurrentPage('settings')}/>
            <span className="text-blue-400 font-bold">Gemini Omni</span>
            <User className="text-gray-400" />
          </div>

          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.length === 0 ? (
              <div className="text-center mt-20">
                <h2 className="text-3xl font-bold mb-8">Hello, Hosam</h2>
                <div className="grid grid-cols-2 gap-4 max-w-xs mx-auto">
                  <button onClick={handleCreateImage} className="bg-[#1a1f3a] p-4 rounded-xl border border-gray-700 flex flex-col items-center gap-2">
                    <Sparkles className="text-blue-400" /> <span>Image</span>
                  </button>
                  <button onClick={() => handleSendMessage("Analyze a video for me")} className="bg-[#1a1f3a] p-4 rounded-xl border border-gray-700 flex flex-col items-center gap-2">
                    <Video className="text-purple-400" /> <span>Video</span>
                  </button>
                </div>
              </div>
            ) : (
              messages.map((msg, i) => (
                <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`p-4 rounded-2xl max-w-[85%] ${msg.role === 'user' ? 'bg-blue-600' : 'bg-[#1a1f3a] border border-gray-800'}`}>
                    {msg.content}
                  </div>
                </div>
              ))
            )}
          </div>

          <div className="p-4 bg-[#0a0e27]">
            <div className="bg-[#1a1f3a] rounded-full flex items-center p-2 border border-gray-700">
              <input 
                className="flex-1 bg-transparent px-4 outline-none" 
                placeholder="Ask anything..." 
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
              />
              <button onClick={() => handleSendMessage()} className="bg-blue-500 p-2 rounded-full"><Send size={18}/></button>
            </div>
          </div>
        </>
      )}

      {/* Settings Screen */}
      {currentPage === 'settings' && (
        <div className="p-6 space-y-6">
          <button onClick={() => setCurrentPage('home')} className="text-gray-400">← Back</button>
          <h2 className="text-2xl font-bold">API Settings</h2>
          <div className="bg-[#1a1f3a] p-4 rounded-xl border border-gray-700">
            <p className="text-xs text-gray-400 mb-2">Hugging Face Read Token</p>
            <input 
              type="password" 
              className="w-full bg-[#0a0e27] p-3 rounded-lg border border-gray-800"
              value={tempApiKey}
              onChange={(e) => setTempApiKey(e.target.value)}
              placeholder="hf_..."
            />
            <button onClick={handleSaveApiKey} className="w-full bg-blue-600 mt-4 py-3 rounded-lg font-bold">
              {apiSaved ? "✓ Saved" : "Save Token"}
            </button>
          </div>
        </div>
      )}

      {/* Footer Nav */}
      <div className="flex justify-around p-4 border-t border-gray-800 bg-[#0a0e27]">
        <Sparkles className={currentPage==='home'?'text-blue-400':'text-gray-500'} onClick={()=>setCurrentPage('home')}/>
        <Mic className="text-gray-500" onClick={()=>setCurrentPage('voice')}/>
        <MoreHorizontal className="text-gray-500" onClick={()=>setCurrentPage('settings')}/>
      </div>
    </div>
  );
};

export default NebulaEdgeApp;
